movies:
  api:
    url: https://wiremock.dev.eroninternational.com
  async:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 50
    thread-name-prefix: MoviesAsync-

cache:
  ttl-minutes: 1
  max-size: 1000
  key-prefix: "movies:page:"

rate-limit:
  capacity: 10
  duration-minutes: 1

spring:
  application:
    name: movies
  cloud:
    compatibility-verifier:
      enabled: false
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha

logging:
  level:
    com.challenge.movies: INFO
