cache:
  ttl-minutes: 1
  max-size: 1000
  key-prefix: "movies:page:"

rate-limit:
  capacity: 10
  duration-minutes: 1

spring:
  data:
    redis:
      enabled: false

logging:
  level:
    com.challenge.movies: DEBUG
