version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: movies-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - movies-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: movies-redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - movies-network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: movies-keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HTTP_PORT=8180
    ports:
      - "8180:8180"
    command:
      - start-dev
      - --http-port=8180
      - --import-realm
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8180/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - movies-network
    volumes:
      - keycloak-data:/opt/keycloak/data
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro

volumes:
  redis-data:
    driver: local
  keycloak-data:
    driver: local

networks:
  movies-network:
    driver: bridge
